repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        files: ^backend/
    -   id: end-of-file-fixer
        files: ^backend/
    -   id: check-yaml
        files: ^backend/
    -   id: check-added-large-files
        files: ^backend/
    -   id: debug-statements
        files: ^backend/
    -   id: check-merge-conflict
        files: ^backend/

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        files: ^backend/

# -   repo: https://github.com/charliermarsh/ruff-pre-commit
#     rev: v0.0.262
#     hooks:
#     -   id: ruff
#         args: [--fix, --exit-non-zero-on-fix]
#         files: ^backend/

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.3.0
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-requests, types-PyYAML]
#         exclude: ^tests/
#         files: ^backend/ 